### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by hirasaki-kaito** [MxsicXYZ/lewds.api#1]
Hello, I Want To Ask What is the Name of Apikey? I'm Looking For Not Found, Hopefully Answered Thank You.

**Comment by Xynnix** [comment]
API Keys, Since I have broken something at the moment, been removed and you can just use the wrapper without. But if i were to re-add API-Keys, they would be requested through discord or emailing.
For now since they aren't needed, here is an updated format:

```js
const lewd = require('lewds.api');
const lewds = new lewd()

lewds.nsfw("slap").then(img => {
    console.log(img)
})
```

**Comment by Xynnix** [comment]
You can get an API Key from here on the [dashboard](https://lewds.fun); Just login with discord first and then go to [the docs](https://lewds.fun/docs) for some examples and to see what your key is.
